### ISSUE TITLE
Need more doc regarding frontend

### ISSUE THREAD

**Issue by pierrepo** [Candihub/pixel#53]
Could you please explain a bit more documentation regarding [Front-end build](https://github.com/Candihub/pixel/blob/master/docs/docker.md#front-end-build)?

We need `node` and `yarn` to build a bunch of css files? I'm still missing the point.

**Comment by pierrepo** [comment]
Maybe you could provide a graph (a simple drawing would be enough) explaining how everything is built.

**Comment by jmaupetit** [comment]
No, you are not missing the point. This is why I will dockerize the node stack in a separate PR (see #48).

**Comment by pierrepo** [comment]
Sorry I'm still lost. Why a package manager (`yarn`)?

**Comment by jmaupetit** [comment]
A few notes to make things clearer: Node.js is a run-time environment for executing JavaScript code server-side. It comes with `npm`, the official, historical package manager. `Yarn` is an alternative, more efficient package-manager. In the python's world, you may think of `npm` as `pip` and `yarn` as `Pipenv`. 

Anyway, I am working on the node tool suite dockerization so that you won't need to install them.

**Comment by jmaupetit** [comment]
To fully answer your question, we need a package manager to setup a front-end build environment. `yarn` will fetch and compile dependencies required to compile `scss` files, fetch Zurb's Foundation, etc. (see the `package.json` file).

**Comment by willdurand** [comment]
> As of today, running make boostrap from Quick start fails with error message

I am very confused. The "Requirements" section should avoid this: https://github.com/Candihub/pixel#requirements. On which OS/env did you run the `make bootstrap` command?

**Comment by pierrepo** [comment]
I ran `make bootstrap` on Linux Ubuntu 16.04.3 up-to-date. 

Actually, I was also puzzled with the Docker container in charge of the front end building but that was under development.
I guess I had to install `node.js` + `yarn` by hand. However, this seems now fixed with the Docker container.

I am still concerned by the heaviness related to the front end management.

**Comment by willdurand** [comment]
> I guess I had to install node.js + yarn by hand. However, this seems now fixed with the Docker container.

ah yes, this project does not have a lot of requirements but nodejs/yarn were two hard requirements indeed. Docker should be the only hard requirement in the near future.

> I am still concerned by the heaviness related to the front end management.

We carefully chose the tools here and that is (unfortunately) one of the lightest future-proof and robust frontend solutions. Tools like `autoprefixer` allow to use the latest CSS features (caniuse.com) for all browsers, allowing to quickly develop cross browsers apps (no more "this website only works with Firefox version X.Y"). In addition, SASS/SCSS is a better syntax for writing CSS and no one really wants to write CSS anymore.

We did not use Gulp, Grunt or any other complicated solution because it would mean maintenance burden in the future. We only run two tools, one to convert SCSS into CSS and the other to fix cross-browser compatibility: https://github.com/Candihub/pixel/blob/256b228d008376b94ec1bd658f3daa9569b9cd7c/Makefile#L42-L43. Yet, this setup can be upgraded with more "Post CSS" plugins or to a more complicated solution, later (or not, that's fine too).

It is not because the interface is simple that writing cross-browser CSS is easy/doable 😇

**Comment by pierrepo** [comment]
I have still the impression you excluded simple solutions very soon in this project. Especially since the main objective of Pixel is data upload/storage/selection/download.

Why not a good old link to a CDN with a local `style.css` to custom things if needed? @jmaupetit told me about non-semantic DOM in issue #10 but is this really important at this stage of the project? Shouldn't be the issue of browser compatibility the job of `foundation`/`bootstrap`?

**Comment by willdurand** [comment]
> I have still the impression you excluded simple solutions very soon in this project.

I rather think we did not communicate enough on this topic. We never choose solutions because  "we do that all the time" or "people use to do that" 😉. This frontend setup is the bare minimum, anything below is a no-go because it would slow down the development and create more issues in the future than anything else. Anything above this setup would be overkill given the frontend requirements for this project, as you said. 

> Shouldn't be the issue of browser compatibility the job of foundation/bootstrap?

Not really. They do that internally, but those are frameworks to speed up the development of interfaces, by providing tools (button style, grids, etc.).

**Comment by pierrepo** [comment]
> I rather think we did not communicate enough on this topic.

I agree.

> This frontend setup is the bare minimum, anything below is a no-go because it would slow down the development 

You should have explained this much more I guess. I am still not convinced because of the amount of dependencies (`node.js`, `yarn`, `sass`, `autoprefixer`) you introduced to deal with the front end. You have to be aware that once your work will be over, we (scientists in charge of this project) will be on our own. We will have some work with the Docker, Django, postgresql things. But we probably won't be able to solve any new issue regarding the maintenance of the front end. This is a strong concern I have.

**Comment by willdurand** [comment]
Please, understand that all decisions are made because of what you've written here:

> You have to be aware that once your work will be over, we (scientists in charge of this project) will be on our own.

In addition, everything is documented (or will be) extensively, and there is 1000x more documentation on that frontend toolchain than PostgreSQL on Internet. I would understand concerns related to the database because that kind of stuff is hard or even Docker, but this frontend management thingy is a very very small detail.

**Comment by pierrepo** [comment]
Sorry @willdurand , you cannot make such assertion:

> Please, understand that all decisions are made because of what you've written here:
> 
> > You have to be aware that once your work will be over, we (scientists in charge of this project) will be on our own.

You have to provide elements that support what you are saying.

In addition, to keep this project alive, we will have to deal with:

- the Django/Python machinery (mandatory)
- the PostgreSQL database thing (mandatory)
- Docker to keep everything all together (seems important)
- the front end

It's duable but still a lot of work. To me the actual front end burden seems very heavy to handle, albeit all your kind efforts to ease the process (docs, Docker...). Again, thank you very much for this :+1: 

But:

> Why not a good old link to a CDN with a local style.css to custom things if needed? @jmaupetit told me about non-semantic DOM in issue #10 but is this really important at this stage of the project? 

I need you to convince me I'm wrong. But as a scientist, you have to be aware that:

- you have to bring me a strong rational
- be aware that I'm used to do many approximations. So the argument "having a semantic DOM" does not stand for me since Pixel won't be the next Facebook  ;-)

**Comment by willdurand** [comment]
> you have to bring me a strong rational

- SCSS is a syntax that is easier and more natural than CSS
- You can write CSS in a SCSS file, it just works, so no need to learn a new language
- CSS is flawed and it would be malicious to let you use it

---

> > Why not a good old link to a CDN with a local style.css to custom things if needed? @jmaupetit told me about non-semantic DOM in issue #10 but is this really important at this stage of the project?
>
> I need you to convince me I'm wrong.

I cannot. Your proposal is not an argument or a viable solution but gut feeling.

But, CDN can break. Also, you will not be able to use the app without an Internet connection (say you want to deploy your own instance for some reason, even on your laptop to show it to students/colleagues).

As for the `style.css` file, see the points about CSS above.

NodeJS is a standard now. It starts to be bundled with distributions, just like PHP, Python, Ruby, etc. Yarn is a better dependency management tool than the one built-in in Node (called `npm`). We use Yarn because it ensures 100% reproducibility, so you will always be able to build the CSS.

Last, by using SCSS you get an extra compilation step that can catch potential errors in your style. This is not something you have with CSS, yet a small CSS issue can cause huge rendering problems. This is yet another thing to prevent issues and improve quality.

**Comment by pierrepo** [comment]
Thank you for your answer.

> - SCSS is a syntax that is easier and more natural than CSS
> - You can write CSS in a SCSS file, it just works, so no need to learn a new language
> - CSS is flawed and it would be malicious to let you use it

I don't understand. You tell me that SCSS is a syntax easier and more natural than CSS, but this is still a new syntax to me. Then you tell me that I can use CSS inside a SCSS but that would be malicious to use CSS... So, I'll have to learn SCSS anyway, no? Why not if you beleive it's better than CSS...

> I cannot. Your proposal is not an argument or a viable solution but gut feeling.

Nop. It seems very real to me.

> But, CDN can break

Of course, that is why failbacks are made for. We can also embed the css framwork in the project. That's even more portable.

> NodeJS is a standard now. 
> SCSS you get an extra compilation step that can catch potential errors in your style.

I like those arguments better. But... is it pertinent for the scale and scope of this particular project? And at this stage of the project?

**Comment by willdurand** [comment]
> I don't understand. You tell me that SCSS is a syntax easier and more natural than CSS, but this is still a new syntax to me. Then you tell me that I can use CSS inside a SCSS but that would be malicious to use CSS... So, I'll have to learn SCSS anyway, no? Why not if you beleive it's better than CSS...

Yes. For example, say you want to style a paragraph inside a list item. SCSS lets you write the code below, which precisely express the intent:

``` scss
li {
  p {
    // style (this is a comment BTW, which is more flexible than "/* */" in plain old CSS)
  }
}
```

This is SCSS code because nesting is not possible in CSS. Yet, the rest is plain CSS (except the comments). That's it. SCSS is a superset of CSS, so you only use the syntax improvements you need. For instance, variables. It is not possible to use variables in CSS, but in SCSS you can write:

``` scss
$text-color: #000;

p {
  color: $text-color;
}
```

Nothing fancy, yet very powerful.

> is it pertinent for the scale and scope of this particular project? And at this stage of the project?

We take care of it so you don't have to.
